# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_TRAIN_DATA: train.pkl
  FEATURIZED_TEST_DATA: test.pkl

source_data_url: https://topcoderbucket1.s3.us-east-1.amazonaws.com/data.xml?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEPv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRzBFAiEA19WvUq20zlMCnuy3%2BoV6f4Deqv1HHvjG0fEEK9IVRCgCIHSP2Yn1RKleJX%2BSxGjS15eav89dQHz1oNJoGqdjeBWgKu0CCLT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMNjU2MzU3MzI0MjI1Igy%2BttmO7YybDBnsz3kqwQIFEj3ebOJAmUd5ZpL7bwiGcRlV06KMHbDTJqqW98Bz5InQ5NwA2dmLnsa73OKpvu5fWfN3rC03EEMPVI1Z0dKGPODImLVX4UXZU9fBqvn039cQ06y0dLKLXgTmPtwS7kOw2nmWhJU0Ywm8r1bkWImc2Ab5hGqQRLXZ3j1K2DBJ%2B3yz0zO20WJgALN6G5n8j2EP5xQib8cGfLpOL3ux5oyPxSV%2FOV%2FeklU1f9qLjTFmbWYw2KyPUJXjkaQm79otsDH5LuiCSyYTmGEIFFd1R5eGLjHYWaPKw7Ghkx8sH0x1iIGm%2FA%2F6a54plPrcBOZ9%2BF%2BI2Gwy9vDdQhL9BOGG543wrRid%2FHsVm60CEnHJZjqmPdXP5L0e8zTwXUXjCQgjTYIb84%2B7bHBGklsB%2Bgl%2BrXbUtSj0kygX6a6Yytb3nEz%2FCFkwwMzumQY6swI7BV04NgBxuPP1Sdi2lL9K5I1cYy6vFzdxKKxhxs1y%2BUIFM0ecPNW3Lp39coxKn4WimgIrWYsppZWzXKHFvKhZG%2F8u2d2SMya2pplHLwWXtmKmJvL7s9qDFjuLeeMMcfbi4XYlS8FltYoNbjyxMqHdor1KsIvMGyjBPFg4yy93anK%2F%2BRZj9zmBXWPWIE7dFLfEteZ0PMbZV8IKZyGJg1UkvwvZriSuSRoirwhHXB58ALV%2BGGnhYChcyrmWqMMu2kApBlle2Kq8uoZqwhK8vuIoKgcBJIkg6c8bW%2FeVpS2KzTbPvlKSojUYnNzDnuQxwYQtIS6GTHtouQU6wv3%2FbajOQ188qCp%2Bx%2FUWLS9v59qPmbW75PFZjjOlmClebmMN4tCzqWfAcjArdKEp5PgNdz9gKcBD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20221004T032000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIAZRUPR6XATZMMCVQN%2F20221004%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7c01aeff2a7c4fc6cb7a635963dd54dc7a7b3f762c15833356a6e383d6d829da
source_download_dir:
  data_dir: data
  data_file: data.xml


local_data_dirs:
  - path_to_local_data_1
  - path_to_local_data_2
