# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv

source_data_url: https://topcoderbucket1.s3.us-east-1.amazonaws.com/data.xml?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEO3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRzBFAiA3fBju%2FrXcQ2O3ImtBK2ijKbFyKF2gbyHNDiJ6LX7d4gIhAIeNpGUtlkOgtKg4%2Fuu01XqthJziZAkxbeZU8YjT%2BVGAKu0CCKb%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMNjU2MzU3MzI0MjI1IgwitH2%2FZXiy%2BHcULWkqwQLh2nN%2FxwQymXn%2B98aqAF9EgdjVHqFQ0ca0RdQVIIY2bk1rwDKpri%2F8V8tflLDvdfg3yffWJhh%2Fo5N1Z46eA8QYnsVxCJ8HjYbB9KevCEc4tUdJED%2Bi1%2BbD8fI5ijBqg5kLa%2BXPsxO0Q%2B4HjiISLYLm5OtDz7Y346o7zJOoQa8%2BPgn1P9SM14I8loPq5R1LQ6pN1No51kcmXEvfy2JrzhMgVa2dd9xlR9QhUqpEF%2FnYMQCd8L5Poi71tPTD4ugLuvZWrmficmA7EeXAQ1WmHl66p6Fq%2FrIQBbH83QEGlJ90scjcRZmtwm7QZ3VePsWQJolOcjDPMO2%2FHyUgimikg2uDTPHgSWKtb9Efh7BBquUJmVpkVEmmZVVZuN9Q0vnKpY7GyyB5T78GqYwqT8Y2K40XgfmzWLb2cSQuPFw1mFFFfHIwxb7rmQY6swIyCJTqqsjHxCCiSsssUGqpYqeQaG5UdBadnrL8fPD4fZg07nQTq%2FiZtBYFpW2ZED1HDIttrLOzeL%2BxaSBCBw9ZOKHnlqsm2fhGlCs28rg8plZkritSR9UTWiBUMrg4S9esd6aTdjMiV53ZMBcroTPpbtl0av8aZlO3pHc2UW5N4F689XmIihTxNQ%2FPqTRV24q4Vp03mpEztO7QOcgXnUeVROnzTrZ0XyygBq81NHWVwvTn6AOtJPvEJWa80f2t42rWu02ouC%2B%2FHHluu8gS%2FgQCNQokQ5zy%2BIFQK%2FcCDHefUXO41nH%2BxFqbt4ch8p%2Ff%2BaPVuvtDqpqbt%2FdwKU%2FkWPQ3IvcQGsSVMXiJBHeBh1YQGoGqgAnYaFHndRNaPRWu8kmGc0zLV0qtQCoEfwZllAfz55r6&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20221003T131858Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIAZRUPR6XAROHJFAGU%2F20221003%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=1144015ad9151ac721c80893c2e44deb35f60e6ca7dba76c1c426757fafc32a9
source_download_dir:
  data_dir: data
  data_file: data.xml


local_data_dirs:
  - path_to_local_data_1
  - path_to_local_data_2
